version: '3'
services:
  api:
    container_name: api
    image: kristofposzet1/trainaholic
    ports:
      - '80:5000'
    depends_on:
      arangodb:
        condition: service_healthy
    restart: on-failure

  arangodb:
    container_name: arangodb
    image: arangodb:latest
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=passwd
    healthcheck:
      test: ['CMD', 'nc', '-vz', 'localhost', '8529']
      timeout: 5s
      retries: 10
